package com.mx.teknei.pcabordo.lib.entities;
// Generated 9/09/2015 12:08:38 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SfcrVehiCond generated by hbm2java
 */
public class SfcrVehiCond  implements java.io.Serializable {


     private int idVehiCond;
     private SfemCond sfemCond;
     private SfvhVehi sfvhVehi;
     private Date fchCrea;
     private Boolean stat;
     private String userCrea;
     private String usrModi;
     private Date fchModi;
     private Integer idEsta;
     private Integer idTipo;
     private Integer idConSis;
     private Set sfpfItins = new HashSet(0);

    public SfcrVehiCond() {
    }

	
    public SfcrVehiCond(int idVehiCond, String userCrea) {
        this.idVehiCond = idVehiCond;
        this.userCrea = userCrea;
    }
    public SfcrVehiCond(int idVehiCond, SfemCond sfemCond, SfvhVehi sfvhVehi, Date fchCrea, Boolean stat, String userCrea, String usrModi, Date fchModi, Integer idEsta, Integer idTipo, Integer idConSis, Set sfpfItins) {
       this.idVehiCond = idVehiCond;
       this.sfemCond = sfemCond;
       this.sfvhVehi = sfvhVehi;
       this.fchCrea = fchCrea;
       this.stat = stat;
       this.userCrea = userCrea;
       this.usrModi = usrModi;
       this.fchModi = fchModi;
       this.idEsta = idEsta;
       this.idTipo = idTipo;
       this.idConSis = idConSis;
       this.sfpfItins = sfpfItins;
    }
   
    public int getIdVehiCond() {
        return this.idVehiCond;
    }
    
    public void setIdVehiCond(int idVehiCond) {
        this.idVehiCond = idVehiCond;
    }
    public SfemCond getSfemCond() {
        return this.sfemCond;
    }
    
    public void setSfemCond(SfemCond sfemCond) {
        this.sfemCond = sfemCond;
    }
    public SfvhVehi getSfvhVehi() {
        return this.sfvhVehi;
    }
    
    public void setSfvhVehi(SfvhVehi sfvhVehi) {
        this.sfvhVehi = sfvhVehi;
    }
    public Date getFchCrea() {
        return this.fchCrea;
    }
    
    public void setFchCrea(Date fchCrea) {
        this.fchCrea = fchCrea;
    }
    public Boolean getStat() {
        return this.stat;
    }
    
    public void setStat(Boolean stat) {
        this.stat = stat;
    }
    public String getUserCrea() {
        return this.userCrea;
    }
    
    public void setUserCrea(String userCrea) {
        this.userCrea = userCrea;
    }
    public String getUsrModi() {
        return this.usrModi;
    }
    
    public void setUsrModi(String usrModi) {
        this.usrModi = usrModi;
    }
    public Date getFchModi() {
        return this.fchModi;
    }
    
    public void setFchModi(Date fchModi) {
        this.fchModi = fchModi;
    }
    public Integer getIdEsta() {
        return this.idEsta;
    }
    
    public void setIdEsta(Integer idEsta) {
        this.idEsta = idEsta;
    }
    public Integer getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(Integer idTipo) {
        this.idTipo = idTipo;
    }
    public Integer getIdConSis() {
        return this.idConSis;
    }
    
    public void setIdConSis(Integer idConSis) {
        this.idConSis = idConSis;
    }
    public Set getSfpfItins() {
        return this.sfpfItins;
    }
    
    public void setSfpfItins(Set sfpfItins) {
        this.sfpfItins = sfpfItins;
    }




}


