package com.mx.teknei.pcabordo.lib.entities;
// Generated 8/10/2015 10:59:21 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SfemCond generated by hbm2java
 */
public class SfemCond  implements java.io.Serializable {


     private int idEmpCond;
     private SfpcCata sfpcCata;
     private Integer numLic;
     private Date fchVen;
     private Integer idTipoLic;
     private Integer userCond;
     private Integer passCond;
     private String usrCrea;
     private Date fchCrea;
     private String usrModi;
     private Date fchModi;
     private int idEsta;
     private int idTipo;
     private Set sfcrVehiConds = new HashSet(0);

    public SfemCond() {
    }

	
    public SfemCond(int idEmpCond, String usrCrea, Date fchCrea, int idEsta, int idTipo) {
        this.idEmpCond = idEmpCond;
        this.usrCrea = usrCrea;
        this.fchCrea = fchCrea;
        this.idEsta = idEsta;
        this.idTipo = idTipo;
    }
    public SfemCond(int idEmpCond, SfpcCata sfpcCata, Integer numLic, Date fchVen, Integer idTipoLic, Integer userCond, Integer passCond, String usrCrea, Date fchCrea, String usrModi, Date fchModi, int idEsta, int idTipo, Set sfcrVehiConds) {
       this.idEmpCond = idEmpCond;
       this.sfpcCata = sfpcCata;
       this.numLic = numLic;
       this.fchVen = fchVen;
       this.idTipoLic = idTipoLic;
       this.userCond = userCond;
       this.passCond = passCond;
       this.usrCrea = usrCrea;
       this.fchCrea = fchCrea;
       this.usrModi = usrModi;
       this.fchModi = fchModi;
       this.idEsta = idEsta;
       this.idTipo = idTipo;
       this.sfcrVehiConds = sfcrVehiConds;
    }
   
    public int getIdEmpCond() {
        return this.idEmpCond;
    }
    
    public void setIdEmpCond(int idEmpCond) {
        this.idEmpCond = idEmpCond;
    }
    public SfpcCata getSfpcCata() {
        return this.sfpcCata;
    }
    
    public void setSfpcCata(SfpcCata sfpcCata) {
        this.sfpcCata = sfpcCata;
    }
    public Integer getNumLic() {
        return this.numLic;
    }
    
    public void setNumLic(Integer numLic) {
        this.numLic = numLic;
    }
    public Date getFchVen() {
        return this.fchVen;
    }
    
    public void setFchVen(Date fchVen) {
        this.fchVen = fchVen;
    }
    public Integer getIdTipoLic() {
        return this.idTipoLic;
    }
    
    public void setIdTipoLic(Integer idTipoLic) {
        this.idTipoLic = idTipoLic;
    }
    public Integer getUserCond() {
        return this.userCond;
    }
    
    public void setUserCond(Integer userCond) {
        this.userCond = userCond;
    }
    public Integer getPassCond() {
        return this.passCond;
    }
    
    public void setPassCond(Integer passCond) {
        this.passCond = passCond;
    }
    public String getUsrCrea() {
        return this.usrCrea;
    }
    
    public void setUsrCrea(String usrCrea) {
        this.usrCrea = usrCrea;
    }
    public Date getFchCrea() {
        return this.fchCrea;
    }
    
    public void setFchCrea(Date fchCrea) {
        this.fchCrea = fchCrea;
    }
    public String getUsrModi() {
        return this.usrModi;
    }
    
    public void setUsrModi(String usrModi) {
        this.usrModi = usrModi;
    }
    public Date getFchModi() {
        return this.fchModi;
    }
    
    public void setFchModi(Date fchModi) {
        this.fchModi = fchModi;
    }
    public int getIdEsta() {
        return this.idEsta;
    }
    
    public void setIdEsta(int idEsta) {
        this.idEsta = idEsta;
    }
    public int getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(int idTipo) {
        this.idTipo = idTipo;
    }
    public Set getSfcrVehiConds() {
        return this.sfcrVehiConds;
    }
    
    public void setSfcrVehiConds(Set sfcrVehiConds) {
        this.sfcrVehiConds = sfcrVehiConds;
    }




}


