package com.mx.teknei.pcabordo.lib.entities;
// Generated 9/09/2015 12:08:38 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SfemCond generated by hbm2java
 */
public class SfemCond  implements java.io.Serializable {


     private int idCond;
     private SfpcCata sfpcCata;
     private String numLic;
     private Date fchVen;
     private Integer idTipoLic;
     private String userCond;
     private String passCond;
     private String usrCrea;
     private Date fchCrea;
     private String usrModi;
     private Date fchModi;
     private Integer idEsta;
     private Integer idTipo;
     private Set sfcrVehiConds = new HashSet(0);

    public SfemCond() {
    }

	
    public SfemCond(int idCond, String usrCrea, Date fchCrea) {
        this.idCond = idCond;
        this.usrCrea = usrCrea;
        this.fchCrea = fchCrea;
    }
    public SfemCond(int idCond, SfpcCata sfpcCata, String numLic, Date fchVen, Integer idTipoLic, String userCond, String passCond, String usrCrea, Date fchCrea, String usrModi, Date fchModi, Integer idEsta, Integer idTipo, Set sfcrVehiConds) {
       this.idCond = idCond;
       this.sfpcCata = sfpcCata;
       this.numLic = numLic;
       this.fchVen = fchVen;
       this.idTipoLic = idTipoLic;
       this.userCond = userCond;
       this.passCond = passCond;
       this.usrCrea = usrCrea;
       this.fchCrea = fchCrea;
       this.usrModi = usrModi;
       this.fchModi = fchModi;
       this.idEsta = idEsta;
       this.idTipo = idTipo;
       this.sfcrVehiConds = sfcrVehiConds;
    }
   
    public int getIdCond() {
        return this.idCond;
    }
    
    public void setIdCond(int idCond) {
        this.idCond = idCond;
    }
    public SfpcCata getSfpcCata() {
        return this.sfpcCata;
    }
    
    public void setSfpcCata(SfpcCata sfpcCata) {
        this.sfpcCata = sfpcCata;
    }
    public String getNumLic() {
        return this.numLic;
    }
    
    public void setNumLic(String numLic) {
        this.numLic = numLic;
    }
    public Date getFchVen() {
        return this.fchVen;
    }
    
    public void setFchVen(Date fchVen) {
        this.fchVen = fchVen;
    }
    public Integer getIdTipoLic() {
        return this.idTipoLic;
    }
    
    public void setIdTipoLic(Integer idTipoLic) {
        this.idTipoLic = idTipoLic;
    }
    public String getUserCond() {
        return this.userCond;
    }
    
    public void setUserCond(String userCond) {
        this.userCond = userCond;
    }
    public String getPassCond() {
        return this.passCond;
    }
    
    public void setPassCond(String passCond) {
        this.passCond = passCond;
    }
    public String getUsrCrea() {
        return this.usrCrea;
    }
    
    public void setUsrCrea(String usrCrea) {
        this.usrCrea = usrCrea;
    }
    public Date getFchCrea() {
        return this.fchCrea;
    }
    
    public void setFchCrea(Date fchCrea) {
        this.fchCrea = fchCrea;
    }
    public String getUsrModi() {
        return this.usrModi;
    }
    
    public void setUsrModi(String usrModi) {
        this.usrModi = usrModi;
    }
    public Date getFchModi() {
        return this.fchModi;
    }
    
    public void setFchModi(Date fchModi) {
        this.fchModi = fchModi;
    }
    public Integer getIdEsta() {
        return this.idEsta;
    }
    
    public void setIdEsta(Integer idEsta) {
        this.idEsta = idEsta;
    }
    public Integer getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(Integer idTipo) {
        this.idTipo = idTipo;
    }
    public Set getSfcrVehiConds() {
        return this.sfcrVehiConds;
    }
    
    public void setSfcrVehiConds(Set sfcrVehiConds) {
        this.sfcrVehiConds = sfcrVehiConds;
    }




}


