package com.mx.teknei.pcabordo.lib.entities;
// Generated 30/09/2015 04:22:57 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SfmoHoraSeop generated by hbm2java
 */
public class SfmoHoraSeop  implements java.io.Serializable {


     private int idHoraServOper;
     private SfpcCata sfpcCata;
     private String nomDia;
     private Date horaInicOper;
     private Date horaFinOper;
     private String diaDesc;
     private String usrCrea;
     private Date fchCrea;
     private String usrModi;
     private Date fchModi;
     private int idEsta;
     private Integer idTipo;
     private Integer idConSis;

    public SfmoHoraSeop() {
    }

	
    public SfmoHoraSeop(int idHoraServOper, String usrCrea, Date fchCrea, int idEsta) {
        this.idHoraServOper = idHoraServOper;
        this.usrCrea = usrCrea;
        this.fchCrea = fchCrea;
        this.idEsta = idEsta;
    }
    public SfmoHoraSeop(int idHoraServOper, SfpcCata sfpcCata, String nomDia, Date horaInicOper, Date horaFinOper, String diaDesc, String usrCrea, Date fchCrea, String usrModi, Date fchModi, int idEsta, Integer idTipo, Integer idConSis) {
       this.idHoraServOper = idHoraServOper;
       this.sfpcCata = sfpcCata;
       this.nomDia = nomDia;
       this.horaInicOper = horaInicOper;
       this.horaFinOper = horaFinOper;
       this.diaDesc = diaDesc;
       this.usrCrea = usrCrea;
       this.fchCrea = fchCrea;
       this.usrModi = usrModi;
       this.fchModi = fchModi;
       this.idEsta = idEsta;
       this.idTipo = idTipo;
       this.idConSis = idConSis;
    }
   
    public int getIdHoraServOper() {
        return this.idHoraServOper;
    }
    
    public void setIdHoraServOper(int idHoraServOper) {
        this.idHoraServOper = idHoraServOper;
    }
    public SfpcCata getSfpcCata() {
        return this.sfpcCata;
    }
    
    public void setSfpcCata(SfpcCata sfpcCata) {
        this.sfpcCata = sfpcCata;
    }
    public String getNomDia() {
        return this.nomDia;
    }
    
    public void setNomDia(String nomDia) {
        this.nomDia = nomDia;
    }
    public Date getHoraInicOper() {
        return this.horaInicOper;
    }
    
    public void setHoraInicOper(Date horaInicOper) {
        this.horaInicOper = horaInicOper;
    }
    public Date getHoraFinOper() {
        return this.horaFinOper;
    }
    
    public void setHoraFinOper(Date horaFinOper) {
        this.horaFinOper = horaFinOper;
    }
    public String getDiaDesc() {
        return this.diaDesc;
    }
    
    public void setDiaDesc(String diaDesc) {
        this.diaDesc = diaDesc;
    }
    public String getUsrCrea() {
        return this.usrCrea;
    }
    
    public void setUsrCrea(String usrCrea) {
        this.usrCrea = usrCrea;
    }
    public Date getFchCrea() {
        return this.fchCrea;
    }
    
    public void setFchCrea(Date fchCrea) {
        this.fchCrea = fchCrea;
    }
    public String getUsrModi() {
        return this.usrModi;
    }
    
    public void setUsrModi(String usrModi) {
        this.usrModi = usrModi;
    }
    public Date getFchModi() {
        return this.fchModi;
    }
    
    public void setFchModi(Date fchModi) {
        this.fchModi = fchModi;
    }
    public int getIdEsta() {
        return this.idEsta;
    }
    
    public void setIdEsta(int idEsta) {
        this.idEsta = idEsta;
    }
    public Integer getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(Integer idTipo) {
        this.idTipo = idTipo;
    }
    public Integer getIdConSis() {
        return this.idConSis;
    }
    
    public void setIdConSis(Integer idConSis) {
        this.idConSis = idConSis;
    }




}


