package com.mx.teknei.pcabordo.lib.entities;
// Generated 29/09/2015 01:25:12 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SfpcCata generated by hbm2java
 */
public class SfpcCata  implements java.io.Serializable {


     private int idCata;
     private String codCata;
     private String codCort;
     private String desCort;
     private String usrCrea;
     private Date fchCrea;
     private String usrModi;
     private Date fchModi;
     private Set sfmoHoraSeops = new HashSet(0);

    public SfpcCata() {
    }

	
    public SfpcCata(int idCata, String codCata, String codCort, String desCort, String usrCrea, Date fchCrea) {
        this.idCata = idCata;
        this.codCata = codCata;
        this.codCort = codCort;
        this.desCort = desCort;
        this.usrCrea = usrCrea;
        this.fchCrea = fchCrea;
    }
    public SfpcCata(int idCata, String codCata, String codCort, String desCort, String usrCrea, Date fchCrea, String usrModi, Date fchModi, Set sfmoHoraSeops) {
       this.idCata = idCata;
       this.codCata = codCata;
       this.codCort = codCort;
       this.desCort = desCort;
       this.usrCrea = usrCrea;
       this.fchCrea = fchCrea;
       this.usrModi = usrModi;
       this.fchModi = fchModi;
       this.sfmoHoraSeops = sfmoHoraSeops;
    }
   
    public int getIdCata() {
        return this.idCata;
    }
    
    public void setIdCata(int idCata) {
        this.idCata = idCata;
    }
    public String getCodCata() {
        return this.codCata;
    }
    
    public void setCodCata(String codCata) {
        this.codCata = codCata;
    }
    public String getCodCort() {
        return this.codCort;
    }
    
    public void setCodCort(String codCort) {
        this.codCort = codCort;
    }
    public String getDesCort() {
        return this.desCort;
    }
    
    public void setDesCort(String desCort) {
        this.desCort = desCort;
    }
    public String getUsrCrea() {
        return this.usrCrea;
    }
    
    public void setUsrCrea(String usrCrea) {
        this.usrCrea = usrCrea;
    }
    public Date getFchCrea() {
        return this.fchCrea;
    }
    
    public void setFchCrea(Date fchCrea) {
        this.fchCrea = fchCrea;
    }
    public String getUsrModi() {
        return this.usrModi;
    }
    
    public void setUsrModi(String usrModi) {
        this.usrModi = usrModi;
    }
    public Date getFchModi() {
        return this.fchModi;
    }
    
    public void setFchModi(Date fchModi) {
        this.fchModi = fchModi;
    }
    public Set getSfmoHoraSeops() {
        return this.sfmoHoraSeops;
    }
    
    public void setSfmoHoraSeops(Set sfmoHoraSeops) {
        this.sfmoHoraSeops = sfmoHoraSeops;
    }




}


